# ##############################################################
#                    SayNoToMcLeaks (By rexbut)                #
# ##############################################################
#          
# debug : Debug mode display messages on console
#           
# bungeecord : Do you use a Bungeecord
#           
# commands : Executes commands by Bukkit console
# --------------------------------------------------------------
# | Replace variable   |  Example                              |
# --------------------------------------------------------------
# |  <player>          |  Lesbleu                              |
# |  <uuid>            |  f3345769-4c70-4a9f-9db9-bdb8f9e8a46c |
# |  <displayname>     |  Lesbleu                              |
# |  <ip>              |  127.0.0.1                            |
# --------------------------------------------------------------
debug: false
bungeecord: false
commands:
- kick <player> §cAlt Account detected
- 'say §6<player> §7was §7kicked §7for §7reason §7: §cAlt §cAccount §cdetected'