name: SayNoToMcLeaks
version: 1.6
authors: [rexbut, lesbleu]
main: fr.evercraft.saynotomcleaks.bukkit.BukkitSayNoToMcLeaks
depend: [ProtocolLib]
commands:
  SayNoToMcLeaks:
    description: SayNoToMcLeaks Description
    usage: /SayNoToMcLeaks
    aliases: mcleaks
permissions:
  saynotomcleaks.bypass:
    description: Permission to bypass Alt Account protection
    default: op
  