name: SayNoToMcLeaks
version: 1.0
authors: [rexbut, lesbleu]
main: fr.evercraft.saynotomcleaks.SayNoToMcLeaks
depend: [ProtocolLib]
commands:
  SayNoToMcLeaks:
    description: SayNoToMcLeaks Description
    usage: /SayNoToMcLeaks