# True/False
# Debug mode display messages on console
debug: false

# Replace variable 	: Example 
#----------------------------------------------------------
#	<player> 		: Lesbleu
#	<uuid> 			: f3345769-4c70-4a9f-9db9-bdb8f9e8a46c
#	<displayname> 	: Lesbleu
#	<ip> 			: 127.0.0.1
#----------------------------------------------------------
commands:
- kick <player> &cAlt Account detected
- 'broadcast &6<player> &7was kicked for reason : Alt Account detected'